name: pyright

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyright:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pyright
      run: |
        python -m pip install --upgrade pip pyright==1.1.358
    - name: Check static typing
      run: |
        pyright